language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.6.29
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
