language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.5.9
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
